steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/randomapp1:${SHORT_SHA}', '.']

  - name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/$PROJECT_ID/randomapp1']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'randomapp1', '--image', 'gcr.io/$PROJECT_ID/randomapp1:${SHORT_SHA}', '--region', 'us-central1', '--platform',
            'managed', --port, '80', '--allow-unauthenticated' ]



