steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/randomapp1:${SHORT_SHA}', '.']

  - name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/$PROJECT_ID/randomapp1']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'a${REVISION_ID}', '--image', 'gcr.io/$PROJECT_ID/randomapp1:${SHORT_SHA}', '--region', 'us-central1', '--platform',
            'managed', --port, '80', '--allow-unauthenticated' ]        
            
  - name: 'gcr.io/cloud-builders/gcloud:latest'
    args: [ 'beta', 'run', 'domain-mappings', 'create', --region, 'us-central1', '--service', 'a${REVISION_ID}', '--domain', 'a${REVISION_ID}.billcentric.com']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['dns', 'record-sets', 'create', 'a${REVISION_ID}', '--rrdatas', 'ghs.googlehosted.com',--ttl, '300', '--type','CNAME']


   



