steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/randomapp1:${SHORT_SHA}', '.']

  - name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/$PROJECT_ID/randomapp1']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'a${SHORT_SHA}', '--image', 'gcr.io/$PROJECT_ID/randomapp1:${SHORT_SHA}', '--region', 'us-central1', '--platform',
            'managed', --port, '80', '--allow-unauthenticated' ]        

  - name: 'gcr.io/cloud-builders/gcloud:latest'
    args: [ 'beta', 'run', 'domain-mappings', 'create', --region, 'us-central1', '--service', 'a${SHORT_SHA}', '--domain', 'a${SHORT_SHA}.billcentric.com']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'dns', 'record-sets', 'transaction', 'start', '--zone', 'billcentric']  

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'dns', 'record-sets', 'transaction', 'add', 'ghs.googlehosted.com.', '--name', 'a${SHORT_SHA}.billcentric.com.',--ttl, '300', '--type','CNAME', '--zone', 'billcentric']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'dns', 'record-sets', 'transaction', 'execute', '--zone', 'billcentric']