steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/randomapp1:${SHORT_SHA}', '.']

  - name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/$PROJECT_ID/randomapp1']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'a${SHORT_SHA}', '--image', 'gcr.io/$PROJECT_ID/randomapp1:${SHORT_SHA}','--vpc-connector' ,'hecbilling-connector','--region', 'us-east1', '--platform',
            'managed', --port, '80', '--allow-unauthenticated' ]        

